---
driver:
  name: vagrant
  provider: cloudstack
  customize:
    host:                   <%= ENV["CLOUDSTACK_HOST"] %>
    api_key:                <%= ENV['CLOUDSTACK_API_KEY'] %>
    secret_key:             <%= ENV['CLOUDSTACK_SECRET_KEY'] %>
    network_name:           <%= ENV["NETWORK_NAME"] %>
    zone_name:              <%= ENV["ZONE_NAME"] %>
    service_offering_name:  <%= ENV["SERVICE_OFFERING_NAME"] %>
    pf_ip_address:          <%= ENV["PUBLIC_SOURCE_NAT_IP"] %>
    expunge_on_destroy:     True
    pf_open_firewall:       False
    pf_trusted_networks:
    - <%= ENV["TRUSTED_NETWORKS"]  %>
    ssh_user:               <%= ENV["SSH_USER"] || 'vagrant' %>

provisioner:
  name: chef_solo
  require_chef_omnibus:     <%= ENV['OMNIBUS_CHEF_CLIENT_VERSION'] || '12.11' %>
  kitchen_root:             /home/<%= ENV['SSH_USER'] %>/kitchen
  root_path:                /home/<%= ENV['SSH_USER'] %>/kitchen
  data_bags_path:           test/fixtures/data_bags
  retry_on_exit_code:
   - 35
  max_retries: 1
  client_rb:
    exit_status: enabled
    client_fork: false

verifier:
  name:       busser
  root_path:  /home/<%= ENV['SSH_USER'] %>/verifier

platforms:
  - name: 'CentOS7'
    driver:
      box: <%= ENV['LINUX_TEMPLATE_NAME'] %>

suites:
  - name: default
    driver:
      customize:
        port_forwarding_rules:
        - privateport: 443
          publicport: 50001
          generate_firewall: True
    run_list:
      - recipe[bubble::default]
    attributes:
      authorization:
        sudo:
          users:
           - <%= ENV["SSH_USER"] || 'vagrant' %>
  - name: mgt-kvm-acs
    driver:
      customize:
        disk_offering_name:     <%= ENV["DISK_OFFERING_NAME"] %>
        port_forwarding_rules:
        - privateport: 443
          publicport: 50002
          generate_firewall: True
    run_list:
      - recipe[bubble::default]
    attributes:
      bubble:
        data_disk: true
      authorization:
        sudo:
          users:
           - <%= ENV["SSH_USER"] || 'vagrant' %>
  - name: mgt-kvm-cosmic
    driver:
      customize:
        disk_offering_name:     <%= ENV["DISK_OFFERING_NAME"] %>
        port_forwarding_rules:
        - privateport: 443
          publicport: 50003
          generate_firewall: True
    run_list:
      - recipe[bubble-cookbook-support::before_master_cookbook]
      - recipe[bubble::default]
    attributes:
      bubble:
        data_disk: true
      authorization:
        sudo:
          users:
           - <%= ENV["SSH_USER"] || 'vagrant' %>
  - name: mgt-kvm-basic-cosmic
    driver:
      customize:
        disk_offering_name:     <%= ENV["DISK_OFFERING_NAME"] %>
        port_forwarding_rules:
        - privateport: 443
          publicport: 50004
          generate_firewall: True
    run_list:
      - recipe[bubble-cookbook-support::before_master_cookbook]
      - recipe[bubble::default]
    attributes:
      bubble:
        data_disk: true
      authorization:
        sudo:
          users:
           - <%= ENV["SSH_USER"] || 'vagrant' %>
